### ISSUE TITLE
Newby to Threat Diagrams

### ISSUE THREAD

**Issue by breezy2u** [mike-goodwin/owasp-threat-dragon-desktop#157]
I'm having trouble understanding the difference between the objects in the application and how they relate to my system diagram. Are my SQL servers a process or a store? What about a windows server? Or a web server? Or an LDAP server? Am I just an idiot?

**Comment by asumupper** [comment]
SQL Servers are databases, qualifying as Data Stores. Windows servers, web servers and ldap servers are Processes.

**Comment by jgadsden** [comment]
Hello @breezy2u , certainly you are not an idiot :-) because these are very good fundamental questions. 

An SQL server may be represented by both a process and a data store, if both are part of the threat surface. A threat model is not a 1:1 correspondance to a system diagram - they are different perspectives on the same system, and they result in very different diagrams (usually).

There are various threat modellig resources that may help you - have you tried the Threat Modeling cheat sheet?
https://cheatsheetseries.owasp.org/cheatsheets/Threat_Modeling_Cheat_Sheet.html

Also if you are an OWASP member then the OWASP slack channel #threat-modeling is a good forum

Hope this helps,
Jon

**Comment by breezy2u** [comment]
Thank you! I will review the cheat sheet. I was able to find a sample web
application threat model and I think it may have cleared up some things for
me. I think I did a threat three a million years ago but I think I beered
those brain cells.
