### ISSUE TITLE
can't open local file

### ISSUE THREAD

**Issue by haishan-wu** [mike-goodwin/owasp-threat-dragon-desktop#166]
dear  writer：
    I used owasp-threat-dragon-desktop on win10  , i can saved file ,but i can't open it again.

**Comment by jgadsden** [comment]
Hello @haishan-wu , this depends on your Windows configuration, but for my Windows10 machine the default locationn is in the 'Documents' folder. Could you see if it is in the equivalent folder on your machine?

Otherwise search for 'new-model.json' to find it, or whatever filename you used.

Are you using the latest version 1.3? It can be found here:
https://github.com/OWASP/threat-dragon-desktop/releases/download/v1.3/OWASP-Threat-Dragon-Setup-1.3.0.exe

**Comment by jgadsden** [comment]
This could be added to the FAQs?
