### ISSUE TITLE
Multiple security vulnerabilities according to 'npm audit'

### ISSUE THREAD

**Issue by callebokedal** [mike-goodwin/owasp-threat-dragon-desktop#41]
`npm audit` 

returns

- 4 high
- 8 moderate
- 16 low

security issues for version `0.5.1`.

(But seems to be a great tool apart from this :-) )

**Comment by mike-goodwin** [comment]
Thank you for your interest in Threat Dragon!

Closing this issue since I now fixed all production vulnerabilities except 1 medium severity in jQuery via JointJS. There is a fix for this in JointJS v3 but this cause multiple breaking changes and there are no docs for the version yet. I will revisit when the docs come out.

Also, there are still vulnerabilities in the dev dependencies but I'm not prioritising those at the moment.
