### ISSUE TITLE
Spaces in property name get screwed up 

### ISSUE THREAD

**Issue by btopalka** [mike-goodwin/owasp-threat-dragon-desktop#46]
When adding a description of a flow with spacing is out of wack. 
![image](https://user-images.githubusercontent.com/1424806/55639539-9ef44e80-5797-11e9-9eb2-920a054b2643.png)

**Comment by mike-goodwin** [comment]
Thank you for your interest in Threat Dragon.

This issue is in [owasp-threat-dragon-core](https://github.com/mike-goodwin/owasp-threat-dragon-core) and is fixed in commit [f30c579f309d300389d2f00791afe17a48b9e5d0](https://github.com/mike-goodwin/owasp-threat-dragon-core/commit/f30c579f309d300389d2f00791afe17a48b9e5d0) it will be merged into the next release of desktop.
